/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and should not be edited.
// See https://nextjs.org/docs/app/api-reference/config/typescript for more information.
